// Generated by CoffeeScript 1.8.0
(function() {
  module.exports = function(grunt) {
    grunt.initConfig({
      cfg: {
        coffeeFiles: ['assets/coffee/app.coffee']
      },
      imagemin: {
        dist: {
          options: {
            optimizationLevel: 3
          },
          files: [
            {
              expand: true,
              cwd: 'assets/images',
              src: ['**/*.{png,jpg,gif}'],
              dest: 'public/img'
            }
          ]
        },
        dev: {
          options: {
            optimizationLevel: 1
          },
          files: [
            {
              expand: true,
              cwd: 'assets/images',
              src: ['**/*.{png,jpg,gif}'],
              dest: 'public/img'
            }
          ]
        }
      },
      clean: {
        all: ['.tmp/**/*', 'public/img/*', 'public/css/*', 'public/js/*']
      },
      coffee: {
        options: {
          bare: true,
          sourceMap: true
        },
        build: {
          files: {
            '.tmp/js/application.js': '<%= cfg.coffeeFiles %>'
          }
        }
      },
      compass: {
        dist: {
          options: {
            sourceMap: true,
            sassDir: 'assets/scss',
            cssDir: '.tmp/css',
            imagesDir: 'public/img',
            javascriptsDir: 'public/js',
            environment: 'production',
            outputStyle: 'compressed',
            watch: true,
            clean: true
          }
        },
        dev: {
          options: {
            sourceMap: true,
            sassDir: 'assets/scss',
            cssDir: '.tmp/css',
            imagesDir: 'public/img',
            javascriptsDir: 'public/js',
            environment: 'development',
            outputStyle: 'compact',
            watch: true,
            clean: true
          }
        }
      },
      copy: {
        assets: {
          files: [
            {
              expand: true,
              cwd: 'assets/js',
              src: ['**'],
              dest: 'public/js'
            }
          ]
        }
      },
      uglify: {
        build: {
          options: {
            mangle: true,
            compress: true
          },
          files: [
            {
              expand: true,
              cwd: 'assets/js',
              src: '**/*.js',
              dest: 'public/js'
            }
          ]
        }
      },
      cssmin: {
        build: {
          files: [
            {
              expand: true,
              cwd: '.tmp/css',
              src: ['*.css', '!*.min.css'],
              dest: 'release/css',
              ext: '.min.css'
            }
          ]
        }
      },
      watch: {
        scripts: {
          files: 'public/**/*.coffee',
          tasks: ['coffee']
        },
        assets: {
          files: 'assets/images/*',
          tasks: ['imagemin:dev']
        }
      }
    });
    grunt.loadNpmTasks('grunt-contrib-clean');
    grunt.loadNpmTasks('grunt-contrib-coffee');
    grunt.loadNpmTasks('grunt-contrib-compass');
    grunt.loadNpmTasks('grunt-contrib-copy');
    grunt.loadNpmTasks('grunt-contrib-cssmin');
    grunt.loadNpmTasks('grunt-contrib-imagemin');
    grunt.loadNpmTasks('grunt-contrib-uglify');
    grunt.loadNpmTasks('grunt-connect-watch');
    grunt.registerTask('build', ['clean:all', 'imagemin:dev', 'coffee', 'uglify:build', 'compass:dev', 'cssmin:build']);
    return grunt.registerTask('deploy', ['clean:all', 'imagemin:dist', 'coffee', 'uglify:build', 'compass:dist', 'cssmin:build']);
  };

}).call(this);

//# sourceMappingURL=Gruntfile.js.map
