<!DOCTYPE html>
<html lang="en" ng-app="PraxusARMA">
	<head>
		<title>PraxusARMA</title>
        <link href="css/index.css" rel="stylesheet" type="text/css" />
        <link rel="stylesheet" href="//ajax.googleapis.com/ajax/libs/angular_material/0.7.1/angular-material.min.css">
	</head>
	<body>
		<?php echo $this->getContent(); ?>
        <script src="//ajax.googleapis.com/ajax/libs/angularjs/1.3.6/angular.min.js"></script>
        <script src="//ajax.googleapis.com/ajax/libs/angularjs/1.3.6/angular-animate.min.js"></script>
        <script src="//ajax.googleapis.com/ajax/libs/angularjs/1.3.6/angular-aria.min.js"></script>
        <script src="//ajax.googleapis.com/ajax/libs/angularjs/1.3.6/angular-route.min.js"></script>
        <script src="//ajax.googleapis.com/ajax/libs/angular_material/0.7.1/angular-material.min.js"></script>
        <script src="js/app.js"></script>
	</body>
</html>